# Generated by Django 3.1.6 on 2021-02-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='character', verbose_name='Image Thumbnail'),
        ),
    ]
